### ISSUE TITLE
Multiline template strings are indented

### ISSUE THREAD

**Issue by dgreensp** [mooz/js2-mode#227]
Because whitespace is significant in template strings, it would be really helpful if multiline template strings received _no_ indentation on lines after the first.

I'm using template strings as multiline string literals for test case data, and I'd like to be able to write:

```
    cases: [
      {
        input: `
class Foo {
  constructor(x) {
    this.x = x;
  }
}`,
        expected: `
var Foo = function Foo(x) {
  babelHelpers.classCallCheck(this, Foo);

  this.x = x;
};`
      },
      {
        input: ...
        expected: ... etc
```

I'd also like to be able to put Markdown in a template literal:

```
content = `This is a paragraph.

And this is another paragraph.`;
```

However, the extra spaces from js2-mode's indentation create Markdown code blocks once they reach 4 spaces!

I hope you'll consider not indenting subsequent lines of template strings, if it isn't too difficult to implement.

**Comment by dgutov** [comment]
It's pretty easy, thanks for the report.

It's also fixed in `js-mode` now, in Emacs master.

**Comment by zilongshanren** [comment]
@dgutov 
How could I re-enable multiline string indent, I often write some HTML template in the template string, but the indent is broken, I have to manually adjust them which is really annoying..

Any workarounds? thanks.

**Comment by dgutov** [comment]
@zilongshanren You can use Emacs 25.1 and apply the patch below:

```diff
diff --git a/lisp/progmodes/js.el b/lisp/progmodes/js.el
index f024d39..f911119 100644
--- a/lisp/progmodes/js.el
+++ b/lisp/progmodes/js.el
@@ -2200,7 +2200,8 @@ js-indent-line
   (let* ((parse-status
           (save-excursion (syntax-ppss (point-at-bol))))
          (offset (- (point) (save-excursion (back-to-indentation) (point)))))
-    (unless (nth 3 parse-status)
+    (if (nth 3 parse-status)
+        'noindent
       (indent-line-to (js--proper-indentation parse-status))
       (when (> offset 0) (forward-char offset)))))
 
```

If that's the behavior you desire, you should file a feature request for Emacs.

**Comment by zilongshanren** [comment]
@dgutov  
Thanks, after applying this patch, I still can't indent the HTML tag property, but the TAB key for indenting works now.

**Comment by dgutov** [comment]
> I still can't indent the HTML tag property

I'm not sure what that means.

**Comment by zilongshanren** [comment]
@dgutov

```js
`
    <ui-prop
      :name="target.name"
      :indent="indent"
      style="padding-top: 10px;"
      auto-height
    >
      <div class="layout vertical flex-1">
        <div class="layout horizontal">
<ui-node class="flex-1" v-value="target.value.target.value.uuid"></ui-node>
          <ui-select class="flex-1" v-value="target.value.component.value">
            <option v-for="item in components" :value="item">
              {{item}}
            </option>
          </ui-select>
          <ui-select class="flex-1" v-value="target.value.handler.value">
            <option v-for="item in handlers" :value="item">
              {{item}}
            </option>
          </ui-select>
        </div>
        <div class="layout horizontal" style="padding-top: 10px;">
          <div class="label" style="white-space:nowrap;padding-right:10px;padding-top:2px;">
          Event Argument
          </div>
          <ui-input class="flex-1" v-value="target.value.customEventData.value"></ui-input>
        </div>
    </div>
    </ui-prop>
  `
```

Suppose I have a template string above, I can't indent the sentence `<ui-node class="flex-1" v-value="target.value.target.value.uuid"></ui-node>` to it's parent ndoe.

Hope this make things more clearer.

**Comment by dgutov** [comment]
I see. Indeed, `indent-relative` only considers the previous line.

**Comment by zilongshanren** [comment]
@dgutov 
Now when editing template string like this, I use `fundamental-mode` to handle the indention problem.
